mynews/urls.py
from django.contrib import admin
from django.urls import path, include
from django_summernote import urls as summernote_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mynewsapp.urls')),
    path('', include('django.contrib.auth.urls')),
    path('summernote/', include(summernote_urls)),
    
]

mynewsapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import custom_logout
from .views import NewsDetail

urlpatterns =  [
    path('home/', views.home, name='home'),
    path('', views.NewsList.as_view(), name="home"),
    path('add_news_post/', views.AddNewsPost.as_view(), name="add_news_post"),
    path('login_user/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('signup_user/', views.signup_user, name='signup'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('news/<slug:slug>', views.NewsDetail.as_view(), name='article'),
    path('news/edit/<slug:slug>', views.UpdateNews.as_view(), name='edit'),
    path('news/delete/<slug:slug>', views.DeleteNews.as_view(), name='delete'),
    path('like/<slug:slug>', views.Like.as_view(), name='news_like'),
 ] 

mynewsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify

# Create your models here.

User = get_user_model()

STATUS = (
    (0, 'Draft'),
    (1, 'Published'),
)


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = CloudinaryField('image', default='placeholder')

    def __str__(self):
        return self.user.username


class Category(models.Model):
    category_name = models.CharField(max_length=25)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Article(models.Model):
    news_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
    Author, on_delete=models.CASCADE, related_name='news_article')
    news_image = CloudinaryField('image', default='placeholder')
    news_overview = models.TextField(null=True)
    news_content = models.TextField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    news_categories = models.ManyToManyField('Category')
    published_status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='news_like', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.news_title

    def number_of_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('home')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.news_title)
        return super().save(*args, **kwargs)


class Comment(models.Model):
    news = models.ForeignKey(Article, on_delete=models.CASCADE,
                             related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return self.user.username        

mynewsapp/forms.py
from django import forms
from mynewsapp.models import Comment
from mynewsapp.models import Article, Author
from django_summernote.widgets import SummernoteWidget
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'placeholder': 'Email Address'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),
        }
        help_texts = {
            'username': '',
            'password1': '',  
            'password2': '',
            'email': '',
        }

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'md-textarea form-control',
        'placeholder': 'Write a comment ...',
        'rows': '4',
    }))

    class Meta:
        model = Comment
        fields = ('content',)


class AddNewsForm(forms.ModelForm):
    news_overview = forms.CharField(widget=SummernoteWidget())
    news_content = forms.CharField(widget=SummernoteWidget())

    class Meta:
        model = Article
        fields = (
            'news_title', 'news_image', 'news_overview',
            'news_content')

        widgets = {
            'news_title': forms.TextInput(attrs={'class': 'form-control'}),
            'news_overview': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write content here ...',
            }),
            'news_content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Write content here ...',
            }),
        }


class UpdateNewsForm(forms.ModelForm):
    news_overview = forms.CharField(widget=SummernoteWidget())
    news_content = forms.CharField(widget=SummernoteWidget())

    class Meta:
        model = Article
        fields = (
            'news_title', 'news_image', 'news_overview',
            'news_content')

        widgets = {
            'news_title': forms.TextInput(attrs={'class': 'form-control'}),
            'news_overview': forms.Textarea(attrs={'class': 'form-control'}),
            'news_content': forms.Textarea(attrs={'class': 'form-control'}),
        }

mynewsapp/views.py
from django.urls import reverse_lazy
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CommentForm, AddNewsForm, UpdateNewsForm
from mynewsapp.models import Article, Author
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Article, Comment
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import logout

class NewsList(ListView):
    model = Article
    template_name = "index.html"
    paginate_by = 6
    
class AddNewsPost(CreateView):
    model = Article
    template_name = ''
    form_class = AddNewsForm
    template_name = 'add_news_post.html'
    success_url = '/home/'

    def form_valid(self, form):
        author = Author.objects.get(user=self.request.user)
        form.instance.author = author
        form.save()
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponse("You are not an Admin.")  

class Like(View):
    def post(self, request, slug, *args, **kwargs):
        news = get_object_or_404(Article, slug=slug)
        if news.likes.filter(id=request.user.id).exists():
            news.likes.remove(request.user)
        else:
            news.likes.add(request.user)

        return HttpResponseRedirect(reverse('article', args=[slug]))

class NewsDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Article.objects.filter(slug=slug)
        news = get_object_or_404(queryset, slug=slug)
        comments = news.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if news.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "article.html",
            {
                "article": news,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "form": CommentForm()
            },
        )
    def post(self, request, slug, *args, **kwargs):

        queryset = Article.objects.filter(published_status=1)
        news = get_object_or_404(queryset, slug=slug)
        comments = news.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if news.likes.filter(id=self.request.user.id).exists():
            liked = True

        form = CommentForm(data=request.POST)
        if form.is_valid():
            form.instance.user = request.user
            comment = form.save(commit=False)
            comment.news = news
            comment.save()
        else:
            form = CommentForm()

        return render(
            request,
            "article.html",
            {
                "article": news,
                "comments": comments,
                "commented": True,
                "form": form,
                "liked": liked
            },
        )

class UpdateNews(UpdateView):
    model = Article
    template_name = 'edit_news_post.html'
    form_class = UpdateNewsForm
    success_url = reverse_lazy('home')

class DeleteNews(DeleteView):
    model = Article
    template_name = 'delete_news_post.html'
    success_url = reverse_lazy('home')    

def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.success(request, ("There was an error logging in, please try again!"))
            return redirect('login')
    else:
        return render(request, 'login.html', {})        

def signup_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request, "Your account has been created successfully!")
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def custom_logout(request):
    logout(request)
    return redirect('/')

def home(request):
    return render(request, 'index.html')

mynewsapp/templates/add_news_post.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<h3 class=" mt-5 text-center">Add News Post</h3>
<br>
<div class="container">
    <div class="col-lg-8 mt-3 mx-auto">
        <div class="form-group">
            <form method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media}}
                {{ form.as_p}}
                <button class="btn btn-secondary" type="submit">Add Post</button>
            </form>
        </div>
    </div>
</div>
{%endblock%}

mynewsapp/templates/article.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-lg-10 mt-3">
            <!-- News title and details -->
            <div class="text-center">
                <br>
                <h2 id="news-title">{{ article.news_title }}</h2>
                <div class="category-name-d">{{ article.created_on }} <span class="c-color"> |
                    </span>{{ article.news_categories.all.0}}</div>
                <br>
            </div>
            <div class="col-md-10 offset-md-1 img-container">
                {% if "placeholder" in article.news_image.url %}
                <img src="{% static 'images/News_Post_Image.jpg' %}" alt="News Post Image" width="100%">
                {% else %}
                <img src=" {{ article.news_image.url }}" alt="News Post Image" width="100%">
                {% endif %}
            </div>
            <!-- News Content -->
            <div class="news-content row mt-5">
                <div class="col-lg-8 mx-auto">
                    <p class="content"> {{ article.news_overview| safe}}</p>
                    <p class="content">
                        {{ article.news_content| safe }}
                    </p>
                </div>
            </div>
            <div class="row">
                <!-- Likes and comments -->
                <div class="col-1">
                    <strong>
                        {% if user.is_authenticated %}
                        <form class="d-inline" action="{% url 'news_like' article.slug %}" method="POST">
                            {% csrf_token %}
                            {% if liked %}
                            <button type="submit" name="news_post" value="{{article.slug}}" class="like-btn"><i
                                    class="fas fa-heart"></i></button>
                            {% else %}
                            <button type="submit" name="news_post" value="{{article.slug}}" class="like-btn"><i
                                    class="far fa-heart"></i></button>
                            {% endif %}
                        </form>
                        {% else %}
                        <span class="text-secondary"><i class="far fa-heart"></i></span>
                        {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ article.number_of_likes }} </span>
                    </strong>
                </div>
                <div class="col-1">
                    {% with comments.count as total_comments %}
                    <strong class="text-secondary"><i class="far fa-comments"></i>

                        {{ total_comments }}</strong>
                    {% endwith %}
                </div>
            </div>
            <hr>
            <!-- Comments Section -->
            <div>
                <div class="section">
                    <div class="container">
                        <h3> Comments: </h3>
                        <div class="row">
                            <div class="col-lg-8 mx-auto">
                                <!-- User comments list -->
                                <div class="media-list  md-5">
                                    {% for comment in comments %}
                                    <div>
                                        <img class="avatar avator-sm mr-4" src="{% static 'images/avatar.png' %}"
                                            alt="Profile Image">
                                        <div class="media-body">
                                            <div class="small-1">
                                                <b>{{ comment.user}}</b>
                                                <time class="ml-4 opacity-70 small-3">{{ comment.created_on}}</time>
                                                <p>{{ comment.content}}</p>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                {% if commented %}
                                <div class="alert alert-success" role="alert">
                                    Your comment is awaiting approval
                                </div>
                                {% else %}
                                {% if user.is_authenticated %}
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="mt-3">
                                        {{ form }}
                                    </div>
                                    <button class="btn btn-primary" type="submit">Comment</button>
                                </form>
                                {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

mynewsapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width">
  <meta name="description"
    content="Stay informed with NEEWO, your go-to source for the latest fashion and beauty news. Get the scoop on runway trends, celebrity styles, makeup tips, and skincare advice. 
    Discover in-depth articles, exclusive interviews, and expert insights in the world of fashion and cosmetics">
  <meta name="keywords" content="Fashion and beauty, Style and makeup tips, Trendy outfits and cosmetics, 
  Fashion and skincare, Celebrity fashion and beauty">
  
  <!-- CDN - Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
 </script>

  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/1bc010baf6.js" crossorigin="anonymous"></script>

  <!-- Link to CSS file -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- Site title and favicon for NewsOnTime-->
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  <title>NEEWO</title>

</head>

<body class="d-flex flex-column h-100">

  <!-- Site NavBar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}"><span class="logo">NEEWO</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
          {% if user.is_superuser%}
          <li class="nav-item">
            <a class="nav-link xs signup" href="{% url 'add_news_post' %}">New Post</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link xs" href="{% url 'logout' %}">SignOut</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link login" href="{% url 'signup' %}">SignUp</a>
          </li>
          <li class="nav-item">
            <a class="nav-link xs signup" href="{% url 'login' %}">Log In</a>
          </li>
          {% endif %}
        </ul>
        <div class="navbar-nav login-info">
          {% if user.is_authenticated %}
          <span class="navbar-text"><strong>Welcome back {{ user.username }} !</strong></span>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>


  <div class="container-fluid p-0">
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    {% endif %}
  </div>

  <main class="flex-shrink-0 main-bg">
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
  </main>

  <!-- Footer -->
  <footer class="footer mt-auto py-3 bg-body-tertiary">
    <div>
      <ul class="social-link">
        <li>
          <a href="https://github.com/" target="_blank"
            aria-label=""><i class="fa-brands fa-github"></i></a>
        </li>
        <li>
          <a href="https://www.linkedin.com/" target="_blank"
            aria-label=""><i class="fa-brands fa-linkedin"></i></a>
        </li>
        <li>
          <a href="https://www.instagram.com/" target="_blank" aria-label="Join us on instagram">
            <i class="fa-brands fa-instagram"></i></a>
        </li>
      </ul>
    </div>

    <p class="footer-text m-0 text-center text-dark">&copy;2024 NEEWO | Privacy Policy</p>
  </footer>
</body>

</html>

mynewsapp/templates/delete_news_post.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2 mt-5">
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    <strong class="warning">Final Confirmation <i class="fa-solid fa-circle-exclamation"></i></strong>
                    <br>
                    <br>
                    <p>This will permanently <span id="delete-txt">Delete</span> the news post. Are you sure you want to proceed?</p>
                    <br>
                    <br>
                    <input class="btn btn-primary" type="submit" value="Confirm"/>
                    <button onclick="window.history.back();" class="btn btn-default" type="button">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}

mynewsapp/templates/edit_news_post.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<h3 class=" mt-5 text-center">Edit News Post</h3>
<br>
<div class="container">
    <div class="col-lg-8 mt-3 mx-auto">
        <div class="form-group">
            <form method="POST" action="{% url 'edit' article.slug  %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p | safe }}
                <button class="btn btn-secondary">Update</button>
            </form>
        </div>
    </div>
</div>
{%endblock%}

mynewsapp/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- Site Header -->
<header>
  <div class="text-center mt-3">
    {% now "l, j F Y" %}
  </div>
</header>

<div class="container-fluid mt-4">
  <div class="row">
    <div class="col-12 mt-3">
      <div class="row">
        <!-- Card's code from Bootstrap  -->
        {% for article in article_list %}
        <div class="col-auto mb-3">
          <!-- <div class="post-container"> -->
          <div class="card">
            <a href="{% url 'article' article.slug  %}" class="news-link">

              {% if "placeholder" in article.news_image.url %}
              <img class="card-img-top" src="{% static 'images/News_Post_Image.jpg' %}" alt="News Image">
              {% else %}
              <img class="card-img-top" src="{{ article.news_image.url }}" alt="News Image">
              {% endif %}
              <div class="card-body mt-3">
                <h5 class="card-title">{{ article.news_title}}</h5>
                <p class="card-text">{{ article.news_overview | safe}}</p>
              </div>
            </a>
            <p class="category-name"><span class="c-color">|</span>{{ article.news_categories.all.0}}</p>

            <!-- Author action - Edite , Delete -->
            {% if user.is_authenticated %}
            {% if user.is_superuser%}
            <div class="manage-news">
              <a href="{% url 'edit' article.slug  %}">Edit <i class="fa-solid fa-pen-to-square"></i></a>
              <a href="{% url 'delete' article.slug  %}">Delete <i class="fa-solid fa-trash"></i></a>
            </div>
            {% endif%}
            {% endif%}
            <hr>
            <p class="date text-muted">{{ article.created_on}}</p>
          </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}
      </div>
      <div class="row">
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
  <!-- Site Pagination -->
  {% if is_paginated %}
  <div class="d-flex justify-content-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Previous</a>
      </li>
      {% endif %}
      {% if page_obj.has_next %}
      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next &raquo;</a></li>
      {% endif %}
    </ul>
  </div>
  {% endif %}
</div>
{%endblock%}